language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t isratzaman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true isratzaman/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker"
  bucket_name: "elasticbeanstalk-us-east-2-629797610914"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"